### PR TITLE
Fix control structure sniff

### PR DESCRIPTION
**Pull request by wilsonge**
The code comment should describe everything

### CODE REVIEW

**Comment by photodude** [comment]
I think you are on the right track here, this seems to have partially fixed the issue. We are correctly getting the new line for the brace, but the indent is not correct now.
See the diff check https://travis-ci.org/photodude/coding-standards/jobs/201704772#L229-L237

**Comment by wilsonge** [comment]
What's the difference between this and the patch-5 branch where it fixes everything?

**Comment by photodude** [comment]
I'll need to look at the control structure brackets sniff, but I think the difference is at the tab to space conversion. I added a `floor()` function to eliminate remainders in the division as I saw PHPCS do in a few sniffs. There might be an issue with how that calculation is applied.

**Comment by wilsonge** [comment]
Ahh this should fix the remainders existing now I *think*

**Comment by photodude** [comment]
Maybe we just ignore this patch-2 branch and fix the CS issues on Patch-5, 
although we should fix the possibility of division remainders in control structure brackets sniff there too.

**Comment by wilsonge** [comment]
No no no. I'll work on reconciling the Control Structure brackets sniff here - we can get this working

**Comment by photodude** [comment]
I'm good with that plan too. Shall we revert the stuff in patch 5 to keep it isolated to just the composer bump?

**Comment by wilsonge** [comment]
Yes!

**Comment by wilsonge** [comment]
That was just me being very careless. Lesson learnt about not typing `git push` whilst on the phone.... again.....

**Comment by wilsonge** [comment]
OK How does this look now?

**Comment by photodude** [comment]
I'm such a noob at git stuff... I assume there must be a cleaner way to revert/roll-back a commit without needing literal revert commits. In any case I have reverted the inadvertent commits.

**Comment by wilsonge** [comment]
Nah I would just use `git reset --soft HEAD~3` too xD

**Comment by wilsonge** [comment]
OK I'm not understanding the PHPCS fail in this PR. Is that expected?

**Comment by photodude** [comment]
It's failing on the CS side now I need to remove some stuff from the travis file I was using to try and debug the issue.
Do you think it's ok to drop the `floor()` to eliminate division remainders? What if the source file had an odd number of spaces?

**Comment by wilsonge** [comment]
I'll find out by adding a test for it :)

**Comment by wilsonge** [comment]
I also meant to flag https://github.com/photodude/coding-standards/blob/patch-2/Joomla/Tests/ControlStructures/ControlStructuresBracketsUnitTest.inc.fixed#L22 this 'expected' result seems wrong to me! We need a tab there surely

**Comment by photodude** [comment]
Since it's a unit test, the tab at that line should be expected to be missing as the controlStructuresBrackets sniff only deals with the brackets. There is another sniff that would fix the code indenting on the control structure with autofixers.

**Comment by wilsonge** [comment]
Ahhh :) I see!

**Comment by photodude** [comment]
Although we might need to consider adding a comment to prevent future questions on that... Over the past year or so I can't count how many times I've had to remind myself why that's not indented.

**Comment by wilsonge** [comment]
This seems to work. The close brace is failing - but I can't see any code for close braces - is that in a separate sniff again?

**Comment by photodude** [comment]
I'm not sure if it's elsewhere or if we should add a closing brace section in this sniff. the original source is a class sniff that we modified the tokens to handle our control structure cases. see [source file](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/PEAR/Sniffs/Classes/ClassDeclarationSniff.php)

That source does not handle the closing brace either....

**Comment by photodude** [comment]
I've reverted the changes in the .travis.yml file if you want to rebase.

**Comment by wilsonge** [comment]
I've reverted the close brackets in the test for now because this should now be good 'as is' but we probably will need to consider this in the not-so-distant future

**Comment by photodude** [comment]
I missed one other change in the .travis.yml file, I have reverted that item now.

**Comment by wilsonge** [comment]
OK This looks happy?

**Comment by photodude** [comment]
I have double checked, the closing brace indent is handled elsewhere. We use Squiz.WhiteSpace.ScopeClosingBrace.Indent which maybe double checked by Generic.WhiteSpace.ScopeIndent.IncorrectExact to sniff for that

Maybe some more comments are needed, and possibly eliminate one of the closing brace checks.

**Comment by wilsonge** [comment]
OK Seems good. I desperately need to go sleep (it's 1.30am here) otherwise i'll be a mess tomorrow morning. But I think this is good to be merged now? Given the unit tests look ok with the spaces.

**Comment by photodude** [comment]
Looking further at this, there are some possible additional overlaps to look at and some of these report spaces rather than tabs  (ran with a modified test file on my local which is slightly behind this in fixes and is still running phpcs 2.7.1)

```php
// This overlap might be expected
5 | WARNING | [ ] Possible parse error: if missing opening or closing brace
 (Joomla.ControlStructures.ControlStructuresBrackets.MissingBrace)
5 | ERROR   | [x] Inline control structures are not allowed
(Generic.ControlStructures.InlineControlStructure.NotAllowed)

 31 | ERROR   | [x] Line indented incorrectly; expected at least 1 tabs, found 0
(Generic.WhiteSpace.ScopeIndent.Incorrect)
 31 | ERROR   | [x] Expected 1 tabs before opening brace; 0 found
(Joomla.ControlStructures.ControlStructuresBrackets.SpaceBeforeBrace)

 33 | ERROR   | [x] Line indented incorrectly; expected 1 tabs, found 1
(Generic.WhiteSpace.ScopeIndent.IncorrectExact)
 33 | ERROR   | [x] Closing brace indented incorrectly; expected 4 spaces, found 6
(Squiz.WhiteSpace.ScopeClosingBrace.Indent)

 38 | ERROR   | [x] Expected 1 newline after opening brace; 2 found
(Joomla.ControlStructures.ControlStructuresBrackets.ExtraNewlineAfterOpenBrace)
 38 | ERROR   | [x] Blank line found at start of control structure
(Squiz.WhiteSpace.ControlStructureSpacing.SpacingAfterOpen)

 44 | ERROR   | [x] Expected 1 newline after opening brace; 3 found
(Joomla.ControlStructures.ControlStructuresBrackets.ExtraNewlineAfterOpenBrace)
 44 | ERROR   | [x] Blank line found at start of control structure
(Squiz.WhiteSpace.ControlStructureSpacing.SpacingAfterOpen)
```

Thanks for the work on this. I'm going to look into the some of these overlaps and the remaining CS errors.

**Pull request merged**
