### PR TITLE
phpcs as package

### PR DESCRIPTION
**Pull request by vess**
- It's a testable package now.
- Did some more exclude in ruleset.xml to not get errors on things we allow.
- Added a first set of new custom sniffs with unit test coming from https://github.com/yaapi/coding-standards but since there are spaces used and we need tabs, sniffs have to be checked carefully so we get no spaces for indenting from the fixers.
- Currently 13 unique error codes; 13 were fixable (100%) and no errors from it's own cs ruleset.

probably not bug free right now, but a start

branched from https://github.com/vess/coding-standards/tree/phpcs-new

### CODE REVIEW

**Comment by photodude** [comment]
@mbabker What do you think? It looks good to me other than the license and some of the renamed variables.

**Comment by mbabker** [comment]
My suggestion to at least [make the current ruleset Composer installable](https://github.com/joomla/coding-standards/pull/115) died off with no activity.  But I obviously support it.  Much easier than dealing with git modules like we do now with the 30+ Framework repositories.

**Comment by vess** [comment]
I'm pretty sure that I also left some arrays as short writing.
Still some work here, will take a look when back home.

**Comment by photodude** [comment]
I agree with the direction of making the ruleset composer installable. 

I do like the addition of the Unit tests in this PR. The was something I was thinking of approaching since  it would give us a better review of how the sniffs are at applying the joomla standards and will help a lot  when we migrate to PHPCS 3.

**Comment by vess** [comment]
Should be a good starting point for fine tuning now.
If you have some "boring" time to spend, a recheck that all errors covered with at least one test would be nice.

**Comment by photodude** [comment]
I'm going to go ahead and merge these changes. Thanks @vess

**Comment by vess** [comment]
There is a bug with the member var check, i forgot to exclude tests when
running on 5.3. But right now I'm not able to fix it because my laptop just
died...

**Comment by photodude** [comment]
Now that this PR is merged, I've got Travis running the checks and can see the failures in 5.3. 
https://travis-ci.org/photodude/coding-standards/jobs/79041021

I'll open an issue in this repository for 5.3 unit test problems

**Pull request merged**
