### PR TITLE
Combine the other two into 1

### PR DESCRIPTION
**Pull request by wilsonge**
This merges the other two PR's into 1. Everything should pass testwise here except the package tag which is an expected failure

### CODE REVIEW

**Comment by wilsonge** [comment]
Umm how the hell did this automerge?

**Comment by wilsonge** [comment]
Oh shit i pushed to `origin` instead of `wilsonge` remote xD

**Comment by photodude** [comment]
Oh my....

**Comment by wilsonge** [comment]
I'm so sorry! Feel free to revert

**Comment by photodude** [comment]
It's all good, Stuff like this happens. I think this pushed through and automerged since patch-5 was an open PR on joomla/coding-standards and the **Allow edits from maintainers** checkbox was checked.

**Pull request merged**
